/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostRouteImport } from './routes/post'
import { Route as MapRouteImport } from './routes/map'
import { Route as LiveRouteImport } from './routes/live'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReelSlugRouteImport } from './routes/reel.$slug'
import { Route as PlaceSlugRouteImport } from './routes/place.$slug'
import { Route as LiveSlugRouteImport } from './routes/live.$slug'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelSlugRoute = ReelSlugRouteImport.update({
  id: '/reel/$slug',
  path: '/reel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceSlugRoute = PlaceSlugRouteImport.update({
  id: '/place/$slug',
  path: '/place/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSlugRoute = LiveSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/live': typeof LiveRouteWithChildren
  '/map': typeof MapRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/live/$slug': typeof LiveSlugRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/reel/$slug': typeof ReelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/live': typeof LiveRouteWithChildren
  '/map': typeof MapRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/live/$slug': typeof LiveSlugRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/reel/$slug': typeof ReelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/live': typeof LiveRouteWithChildren
  '/map': typeof MapRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRoute
  '/live/$slug': typeof LiveSlugRoute
  '/place/$slug': typeof PlaceSlugRoute
  '/reel/$slug': typeof ReelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/live'
    | '/map'
    | '/post'
    | '/profile'
    | '/live/$slug'
    | '/place/$slug'
    | '/reel/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/live'
    | '/map'
    | '/post'
    | '/profile'
    | '/live/$slug'
    | '/place/$slug'
    | '/reel/$slug'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/live'
    | '/map'
    | '/post'
    | '/profile'
    | '/live/$slug'
    | '/place/$slug'
    | '/reel/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  LiveRoute: typeof LiveRouteWithChildren
  MapRoute: typeof MapRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRoute
  PlaceSlugRoute: typeof PlaceSlugRoute
  ReelSlugRoute: typeof ReelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel/$slug': {
      id: '/reel/$slug'
      path: '/reel/$slug'
      fullPath: '/reel/$slug'
      preLoaderRoute: typeof ReelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$slug': {
      id: '/place/$slug'
      path: '/place/$slug'
      fullPath: '/place/$slug'
      preLoaderRoute: typeof PlaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$slug': {
      id: '/live/$slug'
      path: '/$slug'
      fullPath: '/live/$slug'
      preLoaderRoute: typeof LiveSlugRouteImport
      parentRoute: typeof LiveRoute
    }
  }
}

interface LiveRouteChildren {
  LiveSlugRoute: typeof LiveSlugRoute
}

const LiveRouteChildren: LiveRouteChildren = {
  LiveSlugRoute: LiveSlugRoute,
}

const LiveRouteWithChildren = LiveRoute._addFileChildren(LiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  LiveRoute: LiveRouteWithChildren,
  MapRoute: MapRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRoute,
  PlaceSlugRoute: PlaceSlugRoute,
  ReelSlugRoute: ReelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
